### ISSUE TITLE
Wiki needed

### ISSUE THREAD

**Issue by ukdtom** [ZeroQI/Lambda.bundle#1]
In all due respect, but in order to use this, I respectfully ask for a manual (Wiki)

As an idea/starting point, you could look at the WebTools Wiki

**Comment by ukdtom** [comment]
Ohhh....And maybe explain, if there's a relation to HAMA, since that's mentioned in the readme

**Comment by ukdtom** [comment]
And this points to a non existing repo?

`Get the latest source zip in github release for hama https://github.com/ZeroQI/MLE.bundle > "Clone or download > Download Zip (named MLE.bundle-master.zip) and copy the folder inside named MLE.bundle-master into plug-ins folders but rename it into "MLE.bundle" (in short remove '-master' from foldername) :
`

**Comment by ZeroQI** [comment]
Hi ukdtom/dane22! Thanks for taking the time to feedback. Code still changing at this point, just changed to drop-down menus for settings to select file format for export, and once working will update the documentation and publish. Just finished episode thumbs but have to list all eps to find the ones... Not sure if there is a way to load only the given series eps... Still trying to upload collection pic, F11 is very useful but tricky to master

**Comment by ukdtom** [comment]
Still puzzled about how HAMA goes into this?

Having one plugin depending on another is IMHO a road to endless support ;)

**Comment by ZeroQI** [comment]
Apologies, it doesn't... I had copied the readme from hama, and renamed from LME to Lambda which led to the inacuracies, and wanted to finish the code first...

**Comment by ukdtom** [comment]
Still in the code though ;)

https://github.com/ZeroQI/Lambda.bundle/blob/master/Contents/Code/__init__.py#L11
https://github.com/ZeroQI/Lambda.bundle/blob/master/Contents/Code/__init__.py#L399

SO scathing my head here :)

But please consider merging my PR before removing that

**Comment by ZeroQI** [comment]
PR merged
Will finish collection upload asap, then document the read-me then start a proper thread and add it to your repository if possible.

**Comment by ZeroQI** [comment]
I can see you have a wiki but if it's a single page it makes more sense to me in the readme, which users can't say they missed the wiki...
- Created a pull request for my agents in UAS2res.
- It extracted metadata for music, movies, series, seasons, collections so pending feedback from the forum
- left are poster+fanart upload from local files and XML/NFO file creation+import if not in meta or was prev locked/manually edited. 
Working on NFO/XML files XBMC compatible at the moment and will prioritize plex forums feedbacks and

**Comment by ukdtom** [comment]
Make sure this isn't a converter tool to migrate to the dark side ;)

Could be avoided if not exporting nfo, but instead json....


After all, you are the one to reuse afterwards, so a json might actually also be more easy

**Comment by ZeroQI** [comment]
Kodi is best for local playing.
Plex is best for streaming and centralized media files
NFOs are more used therefore make more sense. 
I know JSON is probably easier but NFOs make more sense to 
Currently, most TV series fields supported.

**Comment by ZeroQI** [comment]
NFO files support coming along nicely
If people want to move we shouldn't make it harder. Also, more people may come to us if meta can be migrated both ways if the tool Plex is better which i believe so
Don't see the need for wiki when there is a readme though...

**Comment by ukdtom** [comment]
Well, at the time posted, README.md was a mess ;)

When said, a Wiki allows much better overlook, IMHO, but closing now, since your call

**Comment by ZeroQI** [comment]
will do wiki when I know how to do an index
pasted the readme inside in the meantime.
Would you know how to create an XML element with 'name' or 'text'as
attribute ?
nfo_xml.append( XML.Element(xml_field, **tags ) )  throw an error when
'name' or 'text' used as key in the tags dict...

**Comment by ukdtom** [comment]
You'll have to treat it as real XML

See: https://github.com/ukdtom/epg-dk.bundle/blob/master/Contents/Code/__init__.py

**Comment by ZeroQI** [comment]
@ukdomtom Thanks a lot. it allows me to move forward quite a bit, was stumped
NFOs are better but adding roles to save function proved tricky
