### ISSUE TITLE
How to Use

### ISSUE THREAD

**Issue by Naugrimohtar** [ZeroQI/Lambda.bundle#10]
Hello! Is this still a working plugin? How does it work? I'd love to export the Plex data to NFO files and images and then use MetaX to save that information into the MP4 files.

**Comment by ZeroQI** [comment]
Nobody complained it didn't, so it should be working...
When you update metadata it will save locally the metadata

Please query the agent thread for assistance as i won't have time to fully asist: https://forums.plex.tv/t/rel-lambda-local-assets-metadata-double-agent-for-plex-metadata-export/295681/113

**Comment by nsar1907** [comment]
hello! i wanna say thank you so much for this great plugin.!

is it possible to save all background pics ?

**Comment by ZeroQI** [comment]
https://github.com/ZeroQI/Lambda.bundle/blob/master/Contents/DefaultPrefs.json
active one yes

**Comment by nsar1907** [comment]
> https://github.com/ZeroQI/Lambda.bundle/blob/master/Contents/DefaultPrefs.json
> active one yes

sorry im a noob. may you tell simply what i have to do

**Comment by ZeroQI** [comment]
install it like any other agent
refresh metadata to use it and save data locally
