### ISSUE TITLE
Thanks for all the Effort you have made 

### ISSUE THREAD

**Issue by yes12397** [ZeroQI/Lambda.bundle#13]
i have donated for appreciation for the work you have in here

**Comment by ZeroQI** [comment]
Thank you for that, it is much appreciated, glad you like it, generally people only post bug reports, generally with no logs so it becomes depressing quickly... 
I maintain the series scanner (ASS), youtube, anime (HAMA) agents so it is easy to loose the motivation but donation like this lift the mood definitely.
Thanks !
