### ISSUE TITLE
lambda works on windows but not on unraid!!

### ISSUE THREAD

**Issue by mukalaaa** [ZeroQI/Lambda.bundle#14]
Hello @ZeroQI 
I have been testing your plugin using plex on windows 10. It works with some minor issues but, it works over all.

Now, I moved to unraid because thats where my PLEX server is and i tested it using one file called:

"2 cute 4 porn"
I already have a library there called XXX
but since this is only a test, I created another library called "test" and I put "2 cute 4 porn" in it. 

the plugin does not produce any nfo or jpg files at all. I did metadata refresh many times but still not working!!

I checked the log, I am pretty sure it is not a permission issue 

will you please have a look and tell me what do you think the problem is?

[com.plexapp.agents.lambda.log.zip](https://github.com/ZeroQI/Lambda.bundle/files/4499221/com.plexapp.agents.lambda.log.zip)

**Comment by ZeroQI** [comment]
Logs on the first post! Thanks, that allow quick and precise answers
- It ran, no error but could not find the folder within 5140 records
- "/media/adult_plex/2 cute 4 porn/2 cute 4 porn/2 cute 4 porn/...". Seriously, 3 identically named folders into one another? Not sure if plex database or even my code can cope with that... 
- Try changing the folders names so they are unique, remove from library folder, rescan, add them back, re-scan

**Comment by mukalaaa** [comment]
OK, it was just a test and thats why I did not pay attention to the names of the folders.

I will make the changes you recommended and hopefully it works

Thanks a lot
