### ISSUE TITLE
Add possibility to select path for season posters

### ISSUE THREAD

**Issue by hbooo** [ZeroQI/Lambda.bundle#16]
Hi, 

I'm using Plex and Emby on same folders and I would like to use same metadata for both of them. I think Lambda plugin could help me to do this but there is a problem.

Emby folder for tv posters is : 
tvshow\seasonXX-poster.ext

where Lambda export is : 
tvshow\Season XX\seasonXX.ext

Is there any way to modify lamba export in order that it uses same naming convention that emby (or another) and define root tv show folder for seasons posters export?

Thanks for your help

**Comment by ZeroQI** [comment]
Lambda use the naming conventions that are accepted by the Local media asset agent to load data in Plex. One could edit the file below and the code to change the folder but it will not load the data back through the Local Media Asset agent, therefore no for me...

https://github.com/ZeroQI/Lambda.bundle/blob/master/Contents/DefaultPrefs.json
`  { "id":     "season_poster",  "label": "Season     poster",  "type": "enum",  "default": "Ignored", "values": ["Ignored", "season-specials-poster.ext¦Season{}.ext"                                                                  ] },`

You could have a batch file to create a copy of the file at the right place if you can tolerate two season folders...
