### ISSUE TITLE
is it correct this export?

### ISSUE THREAD

**Issue by Sirfrancis17** [ZeroQI/Lambda.bundle#17]
hi 
i attached my log
[com.plexapp.agents.lambda1.log](https://github.com/ZeroQI/Lambda.bundle/files/4631942/com.plexapp.agents.lambda1.log)
why the program export nfo and images tvshow to inside season's folder?
example:  /house/temporada 01/show.nfo
why dont put this files in root folder tvshow?
/house/show.nfo

**Comment by ZeroQI** [comment]
The restauration is mainly done by local media assets so I followed Plex naming convention for it: https://support.plex.tv/articles/200220717-local-media-assets-tv-shows/

Temporada xx is not a valid season in the scanner code line 64-69:
https://github.com/ZeroQI/Absolute-Series-Scanner/blob/master/Scanners/Series/Absolute%20Series%20Scanner.py

Therefore it consider temporada the series folder.

**Comment by Sirfrancis17** [comment]
Thanks for the answer

**Comment by ZeroQI** [comment]
Changed the scanner code, and the Lambda code for you.
Please test and report

Please consider donating, as i am broke ('es difficil llegar fin del mes y tener que sudar y sudar, pa ganar nuestro pan' if you know the song :p)

**Comment by Sirfrancis17** [comment]
Thanks I'll try it as soon as I can.
