### ISSUE TITLE
how it work?

### ISSUE THREAD

**Issue by Sirfrancis18** [ZeroQI/Lambda.bundle#18]
hi. I try with movies but dont work. attached my config
I try with personal data and plex data. dont work
moviedatabase dont have lambda 
https://i.imgur.com/bjmy7ub.png
https://i.imgur.com/B0wem8p.png
https://i.imgur.com/PKRtF1E.png
https://i.imgur.com/30B6TVB.png
https://i.imgur.com/yAnrzHB.png
in config plugin i try metadata source local and plex. dont work

**Comment by Sirfrancis18** [comment]
i restart the server and only create nfo. (same with plex o local metadata)
<?xml version='1.0' encoding='utf-8'?>
<tvshow xsi="http://www.w3.org/2001/XMLSchema-instance" xsd="http://www.w3.org/2001/XMLSchema">
  <genre>Adventure</genre>
  <genre>Drama</genre>
</tvshow>
this is for shows. Movies dont work
i have all matched in plex. I would like only download nfo and poster. This work if update metadata with personal media?


[com.plexapp.agents.lambda4.log](https://github.com/ZeroQI/Lambda.bundle/files/4658490/com.plexapp.agents.lambda4.log)
[com.plexapp.agents.lambda3.log](https://github.com/ZeroQI/Lambda.bundle/files/4658491/com.plexapp.agents.lambda3.log)

**Comment by Sirfrancis18** [comment]
[com.plexapp.agents.lambda4.log](https://github.com/ZeroQI/Lambda.bundle/files/4658443/com.plexapp.agents.lambda4.log)
[com.plexapp.agents.lambda3.log](https://github.com/ZeroQI/Lambda.bundle/files/4658444/com.plexapp.agents.lambda3.log)

**Comment by Sirfrancis18** [comment]
![image](https://user-images.githubusercontent.com/65591022/82479746-13409d00-9ad3-11ea-9fef-1ec112e6a9ee.png)

**Comment by ZeroQI** [comment]
Hi, you description is very bad to be honest but i think i got the gist of it (i speak french english spanish if it helps, but only english in this thread)
The logs you pasted is useless sadly...

Summary: Movies library using "ThemovieDb" metadata agent don't show 'Lambda' as secondary agent
 
In this code https://github.com/ZeroQI/Lambda.bundle/blob/master/Contents/Code/__init__.py line 705 you need to add the agent string to support it: ", 'com.plexapp.agents.themoviedb'"

**Comment by ZeroQI** [comment]
Please try and report
If it works, please consider donating

**Comment by Sirfrancis18** [comment]
I'm sorry for my bad explanation. 
I wanted to say is if the plugin works choosing "personal media" as agent?  So plex would not have to download data again and lambda would take it from the plex database
Pd: i installed lambda from web tools. Is it a problem?

**Comment by ZeroQI** [comment]
Not sure you can change the library type once created. Please try latest release I just did, it should fix it.

**Comment by Sirfrancis18** [comment]
I try latest releasy. Lambda already appears in the settings for the themoviedatabase but same erros
Not download poster 
Nfo generated are incorrect
This nfo is for the Movie "Noelle" (Correctly identified in plex) 
<?xml version='1.0' encoding='utf-8'?>
<movie xsi="http://www.w3.org/2001/XMLSchema-instance" xsd="http://www.w3.org/2001/XMLSchema">
  <genre>Familia</genre>
  <genre>Comedia</genre>
  <director>Marc Lawrence</director>
  <credits>Marc Lawrence</credits>
  <country>USA</country>
</movie>

**Comment by Sirfrancis18** [comment]
![Screenshot_20200521-135116~2](https://user-images.githubusercontent.com/65591022/82556570-4d10b280-9b6a-11ea-8724-82347110e57c.jpg)

**Comment by ZeroQI** [comment]
I need Lambda agent logs please.

**Comment by Sirfrancis18** [comment]
[com.plexapp.agents.lambda.log](https://github.com/ZeroQI/Lambda.bundle/files/4663406/com.plexapp.agents.lambda.log)

[com.plexapp.agents.lambda2.log](https://github.com/ZeroQI/Lambda.bundle/files/4663408/com.plexapp.agents.lambda2.log)
[com.plexapp.agents.lambda1.log](https://github.com/ZeroQI/Lambda.bundle/files/4663409/com.plexapp.agents.lambda1.log)

I create a new plex server. Add one tvshow and matched with thetvdb. Lambda fail with the same error. Only nfo with two or three lines

**Comment by ZeroQI** [comment]
com.plexapp.agents.lambda2.log is the only one with actionable data and only contain this movie: X:\series\Escuela de brujas (1996)
```
2020-05-21 17:55:19,443 (3620) :  INFO (logkit:16) - SaveFile("X:\series\Escuela de brujas (1996)\poster.jpg", "X:\series\Escuela de brujas (1996)", "series_nfo", "tvshow.nfo"...) xml_field: "{'art': {'poster': {'text': u'X:\\series\\Escuela de brujas (1996)\\poster.jpg'}}}"
2020-05-21 17:55:19,444 (3620) :  INFO (logkit:16) - [?]  plex_value: "X:\series\Escuela de brujas (1996)\poster.jpg", type: "<type 'unicode'>"
2020-05-21 17:55:19,444 (3620) :  INFO (logkit:16) - [?] local_value: "None", type: "<type 'NoneType'>"
```
Delete logs, update metadata for that one movie only, attach logs again
If you cannot attach the logs for your movie, i cannot help you

**Comment by Sirfrancis18** [comment]
I try with one movie and one tvshow
I attach logs and nfo are empty (images not work) 
[com.plexapp.agents.lambda.log](https://github.com/ZeroQI/Lambda.bundle/files/4664194/com.plexapp.agents.lambda.log)
[com.plexapp.agents.lambda1.log](https://github.com/ZeroQI/Lambda.bundle/files/4664195/com.plexapp.agents.lambda1.log)
[com.plexapp.agents.lambda2.log](https://github.com/ZeroQI/Lambda.bundle/files/4664196/com.plexapp.agents.lambda2.log)
[com.plexapp.agents.lambda3.log](https://github.com/ZeroQI/Lambda.bundle/files/4664197/com.plexapp.agents.lambda3.log)

Pd:  X:\series\Escuela de brujas (1996) is a show

**Comment by ZeroQI** [comment]
How do you get 126030 plex entries????
```
2020-05-21 20:50:14,115 (7fab37fff700) :  INFO (__init__:142) - SaveFile("/library/metadata/396991/thumb/1590073353", "/home/gdrive/series/series/Homeland", "series_poster", "poster.ext"...) xml_field: ""
2020-05-21 20:50:14,116 (7fab37fff700) :  DEBUG (networking:143) - Requesting 'http://127.0.0.1:32400/library/metadata/396991/thumb/1590073353'
2020-05-21 20:50:14,127 (7fab37fff700) :  INFO (__init__:210) - [?]  plex_value: "binary...", type: "<type 'str'>"
2020-05-21 20:50:14,127 (7fab37fff700) :  INFO (__init__:210) - [?] local_value: "", type: "<type 'str'>"
2020-05-21 20:50:14,128 (7fab37fff700) :  INFO (__init__:142) - SaveFile("/home/gdrive/series/series/Homeland/poster.jpg", "/home/gdrive/series/series/Homeland", "series_nfo", "tvshow.nfo"...) xml_field: "{'art': {'poster': {'text': '/home/gdrive/series/series/Homeland/poster.jpg'}}}"
```
Looks good to me...
Does "/home/gdrive/series/series/Homeland/poster.jpg" exists?

**Comment by Sirfrancis18** [comment]
![Screenshot_20200521-211709](https://user-images.githubusercontent.com/65591022/82596946-7b14e780-9ba8-11ea-92b8-9dbeb29c3bcf.jpg)
Not exist jpg
126030? I Dont know, chapters maybe?. I delete the logs before run update metadata
I have +3k shows and +12k movies
Why nfo is empty?

**Comment by ZeroQI** [comment]
3k shows and +12k movies => es possible que hay problemas con el volumen >10000 eps o otra limitacion...
No puedo ver a ninguna error en lo logs cuando deberia problemas a escribir al systema de ficheros
Mire al fichero [...]/Plex Media Server/Logs/PMS Plugin Logs/com.plexapp.system.log

**Comment by Sirfrancis18** [comment]
[com.plexapp.system.log](https://github.com/ZeroQI/Lambda.bundle/files/4664531/com.plexapp.system.log)
do you need all logs (5 files) ?

**Comment by ZeroQI** [comment]
no crash nor anything wrong in logs...
I don't know what to advise...

**Comment by Sirfrancis18** [comment]
Ok. Thanks anyway

**Comment by ZeroQI** [comment]
Try to create a library with just one series or movies and see if it helps maybe... It could be linked to your is, a Plex database corruption, file system error but that seem specific to your installation...

**Comment by Sirfrancis18** [comment]
i stop server. delete database.restart plex server. create new 
data base. add 2 o 4 tvshows and movies and the same error . attach logs

[com.plexapp.system.log](https://github.com/ZeroQI/Lambda.bundle/files/4664836/com.plexapp.system.log)
[com.plexapp.agents.lambda.log](https://github.com/ZeroQI/Lambda.bundle/files/4664841/com.plexapp.agents.lambda.log)

[com.plexapp.agents.lambda1.log](https://github.com/ZeroQI/Lambda.bundle/files/4664843/com.plexapp.agents.lambda1.log)
I Installed plex server in different pc

**Comment by ZeroQI** [comment]
```
2020-05-21 23:13:27,592 (1d90) :  INFO (logkit:16) - SaveFile("/library/metadata/4/thumb/1590095568", "W:\Series\_Subir nuevas aqui_\A Tres Metros Sobre El Cielo", "series_poster", "poster.ext"...) xml_field: ""
2020-05-21 23:13:27,592 (1d90) :  DEBUG (networking:143) - Requesting 'http://127.0.0.1:32400/library/metadata/4/thumb/1590095568'
2020-05-21 23:13:27,611 (1d90) :  INFO (logkit:16) - [?]  plex_value: "binary...", type: "<type 'str'>"
2020-05-21 23:13:27,612 (1d90) :  INFO (logkit:16) - [?] local_value: "", type: "<type 'str'>"
2020-05-21 23:13:27,612 (1d90) :  INFO (logkit:16) - SaveFile("W:\Series\_Subir nuevas aqui_\A Tres Metros Sobre El Cielo\poster.jpg", "W:\Series\_Subir nuevas aqui_\A Tres Metros Sobre El Cielo", "series_nfo", "tvshow.nfo"...) xml_field: "{'art': {'poster': {'text': u'W:\\Series\\_Subir nuevas aqui_\\A Tres Metros Sobre El Cielo\\poster.jpg'}}}"
2020-05-21 23:13:27,614 (1d90) :  INFO (logkit:16) - [?]  plex_value: "W:\Series\_Subir nuevas aqui_\A Tres Metros Sobre El Cielo\poster.jpg", type: "<type 'unicode'>"
2020-05-21 23:13:27,614 (1d90) :  INFO (logkit:16) - [?] local_value: "None", type: "<type 'NoneType'>"
```
Need to check source for possible bug not creating any logs...

**Comment by Sirfrancis18** [comment]
> ```
> 2020-05-21 23:13:27,592 (1d90) :  INFO (logkit:16) - SaveFile("/library/metadata/4/thumb/1590095568", "W:\Series\_Subir nuevas aqui_\A Tres Metros Sobre El Cielo", "series_poster", "poster.ext"...) xml_field: ""
> 2020-05-21 23:13:27,592 (1d90) :  DEBUG (networking:143) - Requesting 'http://127.0.0.1:32400/library/metadata/4/thumb/1590095568'
> 2020-05-21 23:13:27,611 (1d90) :  INFO (logkit:16) - [?]  plex_value: "binary...", type: "<type 'str'>"
> 2020-05-21 23:13:27,612 (1d90) :  INFO (logkit:16) - [?] local_value: "", type: "<type 'str'>"
> 2020-05-21 23:13:27,612 (1d90) :  INFO (logkit:16) - SaveFile("W:\Series\_Subir nuevas aqui_\A Tres Metros Sobre El Cielo\poster.jpg", "W:\Series\_Subir nuevas aqui_\A Tres Metros Sobre El Cielo", "series_nfo", "tvshow.nfo"...) xml_field: "{'art': {'poster': {'text': u'W:\\Series\\_Subir nuevas aqui_\\A Tres Metros Sobre El Cielo\\poster.jpg'}}}"
> 2020-05-21 23:13:27,614 (1d90) :  INFO (logkit:16) - [?]  plex_value: "W:\Series\_Subir nuevas aqui_\A Tres Metros Sobre El Cielo\poster.jpg", type: "<type 'unicode'>"
> 2020-05-21 23:13:27,614 (1d90) :  INFO (logkit:16) - [?] local_value: "None", type: "<type 'NoneType'>"
> ```
> 
> Need to check source for possible bug not creating any logs...

Do you need any log?

**Comment by ZeroQI** [comment]
Please try latest version
Note: if there is info in plex and locally it will not update plex nor local info due to settings
`[ ] Prefs['metadata_source'  ] = 'Ignored'   , default = 'local'`

**Comment by Sirfrancis18** [comment]
[com.plexapp.agents.lambda.log](https://github.com/ZeroQI/Lambda.bundle/files/4680556/com.plexapp.agents.lambda.log)
[com.plexapp.agents.lambda1.log](https://github.com/ZeroQI/Lambda.bundle/files/4680557/com.plexapp.agents.lambda1.log)
[com.plexapp.agents.lambda2.log](https://github.com/ZeroQI/Lambda.bundle/files/4680558/com.plexapp.agents.lambda2.log)
[com.plexapp.agents.lambda3.log](https://github.com/ZeroQI/Lambda.bundle/files/4680559/com.plexapp.agents.lambda3.log)
[com.plexapp.agents.lambda4.log](https://github.com/ZeroQI/Lambda.bundle/files/4680560/com.plexapp.agents.lambda4.log)
[com.plexapp.agents.lambda5.log](https://github.com/ZeroQI/Lambda.bundle/files/4680561/com.plexapp.agents.lambda5.log)

good morning
He tried again with some series and it has not worked.
I have tried local, plex and ignore but it did not work
I attach the logs

**Comment by ZeroQI** [comment]
```
2020-05-26 09:24:11,329 (7fe857fff700) :  CRITICAL (storage:89) - Exception writing to /home/gdrive/series/series/Cougar Town (2009)/T1/tvshow.nfo (most recent call last):
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-e3c1f7bcd/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/components/storage.py", line 83, in save
    f.close()
IOError: [Errno 5] Input/output error
```

Hay un problema al nivel del systema de ficheros del systema operativo...
No se parece un probmema de Lambda...

**Comment by Sirfrancis18** [comment]
> ```
> 2020-05-26 09:24:11,329 (7fe857fff700) :  CRITICAL (storage:89) - Exception writing to /home/gdrive/series/series/Cougar Town (2009)/T1/tvshow.nfo (most recent call last):
>   File "/usr/lib/plexmediaserver/Resources/Plug-ins-e3c1f7bcd/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/components/storage.py", line 83, in save
>     f.close()
> IOError: [Errno 5] Input/output error
> ```
> 
> Hay un problema al nivel del systema de ficheros del systema operativo...
> No se parece un probmema de Lambda...

it's work but only shows one actor tag. it's a bug?

[tvshow.txt](https://github.com/ZeroQI/Lambda.bundle/files/4830010/tvshow.txt)

**Comment by ZeroQI** [comment]
This is a "Riverdale" series... Your initial issue is about movies...
If you have multiple actors in Plex, it is a bug and i need the agent logs showing that very same series updated, so update metadata on it, then send attach the Lambda agent logs.

**Comment by Sirfrancis18** [comment]
My initial issue It was with both of us. Series and movies. Now both work but only one actor. 
Attached logs
[com.plexapp.agents.lambda.log](https://github.com/ZeroQI/Lambda.bundle/files/4830651/com.plexapp.agents.lambda.log)
[com.plexapp.agents.lambda5.log](https://github.com/ZeroQI/Lambda.bundle/files/4830652/com.plexapp.agents.lambda5.log)
[com.plexapp.agents.lambda3.log](https://github.com/ZeroQI/Lambda.bundle/files/4830653/com.plexapp.agents.lambda3.log)
[com.plexapp.agents.lambda4.log](https://github.com/ZeroQI/Lambda.bundle/files/4830654/com.plexapp.agents.lambda4.log)
[com.plexapp.agents.lambda2.log](https://github.com/ZeroQI/Lambda.bundle/files/4830655/com.plexapp.agents.lambda2.log)
[com.plexapp.agents.lambda1.log](https://github.com/ZeroQI/Lambda.bundle/files/4830656/com.plexapp.agents.lambda1.log)

**Comment by Sirfrancis18** [comment]
Another detail is the agent that uses plex to identify. It is not reflected in the nfo. just put UNKNOWN instead of, for example, thetvdb

`<uniqueid` default="true" type="unknown">269641</uniqueid>
  <title>Chicago P.D. </title>

**Comment by ZeroQI** [comment]
You didn't pick an impacted series to update the metadata, and then attach logs, the logs are filled with parsing entries logs with multiple series running concurently, and since you have 129671 items i cannot see proper one series at a time logs...

That is working as designed in regards to the UNKNOWN.
If you use my agents i can extract the source from the unique id, otherwise it is unknown.
I could use the agent listed under the library [https://support.plex.tv/articles/201638786-plex-media-server-url-commands/ second command output] BUT you can custom select an agent for matching and the result would then be wrong, and the item xml [3rd url output] do not specify it...
If you know a sure value to get the agent custom used on a movie or series then please let me know

Lines 357-358
```
  if '-' in metadata.id:  source, id = metadata.id.split('-', 1)
  else:                   source, id = '', metadata.id 
```

Line 378
`SaveFile(id                                , path, 'movies_nfo', nfo_xml=nfo_xml, dynamic_name=filenoext, xml_field={'uniqueid': {'type': source or 'unknown', 'default': 'true', 'text': id}})`

**Comment by Sirfrancis18** [comment]
when thetvdb agent cannot find the series I use tmdb. Not having lambda for moviedatabase in series does not extract nfo and poster. How can I make the lambda agent appear with the tmdb agent in series?



> If you use my agents i can extract the source from the unique id, otherwise it is unknown.

How can I use your agents?

**Comment by ZeroQI** [comment]
Hama, Youtube agents only... The unique id will include the source [tvdb-xxxx, anidb-xxxx, etc...]
You can modify the nfo changing source to local in settings, but poster changes won't be reflected locally then unless you delete the posters...

**Comment by Sirfrancis18** [comment]
> You can modify the nfo changing source to local in settings, but poster changes won't be reflected locally then unless you delete the posters

si escojo esa opción (local) y no hay ni nfo ni poster (en local), al actualizar los metadatos, los creará?

if there is no poster in local will be created when update metadata?
how can i try Hama and youtube? i only have plex, tmdb, tvdb, local and lambda

**Comment by Sirfrancis18** [comment]
> You didn't pick an impacted series to update the metadata, and then attach logs, the logs are filled with parsing entries logs with multiple series running concurently, and since you have 129671 items i cannot see proper one series at a time logs...

i delete logs
update show "modern family"
i attached logs
[com.plexapp.agents.lambda1.log](https://github.com/ZeroQI/Lambda.bundle/files/4835945/com.plexapp.agents.lambda1.log)
[com.plexapp.agents.lambda2.log](https://github.com/ZeroQI/Lambda.bundle/files/4835947/com.plexapp.agents.lambda2.log)
[com.plexapp.agents.lambda3.log](https://github.com/ZeroQI/Lambda.bundle/files/4835948/com.plexapp.agents.lambda3.log)
[com.plexapp.agents.lambda.log](https://github.com/ZeroQI/Lambda.bundle/files/4835949/com.plexapp.agents.lambda.log)

i hope helps for the export all actors tags

**Comment by ZeroQI** [comment]
si. el parametro esta unicamente utilizado cuando los datos existen en los dos lados, si no hay metadata en local, los creará.
Has anadido Lambda, pues puedes anadir hama y youtube pero hama es para anime principalmente pero functionaria con tvdb pero el matching va a ser peor por series as va a intentar de hacer un match con anidb.net si los series tienen une singula "season"

**Comment by Sirfrancis18** [comment]
> Has anadido Lambda, pues puedes anadir hama y youtube pero hama es para anime principalmente pero functionaria con tvdb pero el matching va a ser peor por series as va a intentar de hacer un match con anidb.net si los series tienen une singula "season"

Me quedare con el UKNOWN entonces

Alguna opcion para que lambda apareza con el agente moviedatabase en las series?
Si hay alguna serie identificada con ese agente (en vez de thetvdb) no exporta nfo ni poster

**Comment by ZeroQI** [comment]
Lambda es una agento secondario, pues debe ser modifivado por cada agente utilisado
Linea 701 se debe anadir el agente correcto nombre:
contributes_to       = ['com.plexapp.agents.hama', 'com.plexapp.agents.thetvdb', 'com.plexapp.agents.none']

agente Contents/Info.plist:
```
  <key>CFBundleIdentifier</key>
  <string>com.plexapp.agents.colima</string>
```
For movies there is 'com.plexapp.agents.themoviedb', i find traces of it for series so added support now

Con la modificacion del codigo ariba, deberia functionar.
UNKNOWN no puedo ser solucionado con los informaciones que tengo actualmente

**Comment by Sirfrancis18** [comment]
ok. intentare a ver si exporta con la nueva linea. Espero que los logs ayuden a encontrar el bug de los actores

**Comment by ZeroQI** [comment]
2020-06-26 10:52:01,793 (7f05fb7fe700) :  INFO (__init__:142) - SaveFile("Phil Traill", "/home/gdrive/series/series/Modern Family/Season 07", "episode_nfo", "Ignored"...) xml_field: "director"
2020-06-26 10:52:01,793 (7f05fb7fe700) :  INFO (__init__:142) - SaveFile("Elaine Ko", "/home/gdrive/series/series/Modern Family/Season 07", "episode_nfo", "Ignored"...) xml_field: "credits"

No puedo encontrar actores en los logs. tienes actores en la interface web de Plex por esta serie?

**Comment by Sirfrancis18** [comment]
si, muchos
ademas en el log me ha puesto el primero
`<actor>
    <role>Jay Pritchett</role>
  </actor>`

**Comment by Sirfrancis18** [comment]
no sé si es mejor que cierre este post y continuar en el #12 ya que es el asunto que se trata ahora (bug de actores)
I do not know if it is better that I close this post and continue in # 12 since it is the issue that is dealt with now (actor bug)

**Comment by ZeroQI** [comment]
normally all list fields allowed one entry only and has been resolved. Let's use #12 if list fields still have issues
