### ISSUE TITLE
spaces in code

### ISSUE THREAD

**Issue by ukdtom** [ZeroQI/Lambda.bundle#3]
I see you want your code to look pretty, and as such, are inserting spaces to make lines with eq. signs adj. in one row.

That is not allowed according to PEP8, and as such, not recommended.

Strongly suggest, that you install a pep8 plugin to your ide

**Comment by ZeroQI** [comment]
Pep 8 aim is to improve readability. You are saying it look pretty (ie more readable?) yet not allowed in PEP8... 
```
Some other good reasons to ignore a particular guideline:
When applying the guideline would make the code less readable, even for someone who is used to reading code that follows this PEP.
```
Hoewever line length might explain why it often give the wrong code line when errors are detected...
 
There is no PEP8 checker for Notepad++ which i exclusively develop with

I do value some recommendation of PEP8 but struggle with changing habits as making one single line 5 does not help my readability of the code, but i may code weirdly, i admit...

**Comment by ukdtom** [comment]
Well, your code, so your call ;)

Just wanted to mention it, in case you didn't knew that.

And FYI: I use this, on both Windows, Mac and Linux
https://code.visualstudio.com/

**Comment by ZeroQI** [comment]
I appreciate your input warmly.
I downloaded it and look really nice and seemingly can support github so will give a try.
Thanks
