### ISSUE TITLE
borked

### ISSUE THREAD

**Issue by yggdrasil75** [ZeroQI/Lambda.bundle#30]
File "C:\Users\Yggdrasil75\AppData\Local\Plex Media Server\Plug-ins\Lambda.bundle\Contents\Code\__init__.py", line 405
    for tag in xml.iterdescendants('Role'      ):  for tag in xml.iterdescendants('Role' ): SaveFile(tag.get('tag'), path, 'movies_nfo', nfo_xml=nfo_xml, xml_field={'actor': {'role': {'text': tag.get('role')}, 'name': {'text': tag.get('tag')}, 'thumb': {'text': tag.get('thumb', '')}}}, multi='actor', tag_multi='role'); roles.append(tag.get('tag'));  roles.append(tag.get('tag'))

SyntaxError: invalid syntax
from log, it appears that the change to init on line 405 has broken the plugin

**Comment by ZeroQI** [comment]
Thanks for spotting, can't have two loops with ':' on the same line...
