### ISSUE TITLE
Question: How to allow Lambda plugin to export data for Audnexus agent?

### ISSUE THREAD

**Issue by linust** [ZeroQI/Lambda.bundle#38]
Trying to wrap my head around where in the code base to change the filter to allow Lambda to export data matched with Audnexus agent. (com.plexapp.agents.audnexus)

https://github.com/djdembeck/Audnexus.bundle

It matches audiobooks (as Albums).

**Comment by ZeroQI** [comment]
https://github.com/djdembeck/Audnexus.bundle/blob/main/Contents/Info.plist
CFBundleIdentifier: **com.plexapp.agents.audnexus**

https://github.com/ZeroQI/Lambda.bundle/blob/master/Contents/Code/__init__.py#L714
add it to the **contributes_to** array
```
class LambdaAlbum(Agent.Album):
  name, primary_provider, fallback_agent, languages = 'Lambda', False, False, [Locale.Language.English, 'fr', 'zh', 'sv', 'no', 'da', 'fi', 'nl', 'de', 'it', 'es', 'pl', 'hu', 'el', 'tr', 'ru', 'he', 'ja', 'pt', 'cs', 'ko', 'sl', 'hr']
  persist_stored_files = False
  contributes_to       = ['com.plexapp.agents.discogs', 'com.plexapp.agents.lastfm', 'com.plexapp.agents.plexmusic', 'com.plexapp.agents.none']
  def search(self, results,  media, lang, manual):  Search(results,  media, lang, manual, 'album')
  def update(self, metadata, media, lang, force ):  Update(metadata, media, lang, force,  'album')
```

**Comment by linust** [comment]
Awesome! Works beautifully
