### ISSUE TITLE
New Agent Support?

### ISSUE THREAD

**Issue by HStep20** [ZeroQI/Lambda.bundle#39]
I expect its not possible, but does this support the new plex agents at all? Ive got it up and running, but had to switch to an old agent in order to get it to work. Thanks!

**Comment by ZeroQI** [comment]
The new agents don't run python so no longer support agents and scanners

External clip:
https://forums.plex.tv/t/rel-lambda-local-assets-metadata-double-agent-for-plex-metadata-export/295681/215?u=zeroqi
