### ISSUE TITLE
Lambda installed but not doing anything

### ISSUE THREAD

**Issue by VirgilThinks** [ZeroQI/Lambda.bundle#40]
I've managed to install Lambda on a Plex Server on Nvidea Shield – it shows up as an agent which I've ticked on. I've also turned on the setting to export movie posters.

When I refresh metadata on a movie, nothing happens. No cover is exported. [com.plexapp.agents.lambda.log](https://github.com/ZeroQI/Lambda.bundle/files/9995050/com.plexapp.agents.lambda.log).

(It would be great if a little more documentation could be added. I'm a bit of a beginner, so for instance it took me ages even to work out that the plugin worked by adding an agent! And another age to work out that it is meant to do its thing upon refreshing metadata.)

Thanks for your help.

**Comment by Scoree** [comment]
Also having this issue with the same error in logs.

**Comment by ZeroQI** [comment]
Error is present in all agents and à Plex error.
What type of main agent are you using? The new plex ones?

**Comment by Scoree** [comment]
I am!
For Hama + Ass i'm actually getting "[errno 13] permission denied", Could this be because my files are hosted on a separate system?

**Comment by ZeroQI** [comment]
New plex agent type libraries do not support third party agents...
Location should not matter but you have rights issue seemingly

**Comment by Scoree** [comment]
They are hosted on a windows system and the server is running from linux, so i guess it's a me problem for the most part
