### ISSUE TITLE
Usage scenario for having a Lambda search agent

### ISSUE THREAD

**Issue by docbill** [ZeroQI/Lambda.bundle#42]
There is a 2019 Amazon Prime TV Series: "Tabitha: Witch of the Order"

It has five 15 minute episodes, and may or may not be the same as the 2017 movie but is not presented in a movie format.

Anything I run the plex scanner, if it is unmatched, plex will match it to a completely random series and mess-up all the metadata.  Because the series does not exist in the tv database, and I for one am not about to submit it without somehow determining if this is the same as the movie.

In anycase, the solution to avoid the random mapping so to search and match to the XBMCnfoTVImporter.  Then since the TV series is matched via my nfo files, plex no longer tries to randomly rematch.   Since it is the goal of Lambda to replace the XBMCnfoTVImporter, this functionality really should be replicated.

Another example, I wanted to remap Doctor Who (2005) into custom order.  I renamed the seasons to avoid conflicts.  e.g. Season 101 instead of Season 1...   For the most part this works.  But at random times plex does things like replace all the episode titles with values like "Episode 1", "Episode 2", ...   The solution to this is once all the metadata is local, to match to the "XBMCnfoTVImporter" so there is never a scan of the TheTVDB.  But I did not present this use-case upfront, because there is another issue with this solution I'm still trying to understand.  So making updates on the basis of this usecase alone does not make sense.

**Comment by docbill** [comment]
One would think using the "Personal Media Shows" agent to do the match would do the same thing.  But after matching with the "Personal Media Shows" agent the series is still shown as unmapped.  After matching with "XBMCnfoTVImporter" the series is shown as mapped.  So only the later actually prevents plex from attempting to rematch when refreshing metadata.

**Comment by ZeroQI** [comment]
In Plex the aent match, not the scanner...
Lambda either save metadata loxally to XMBVC.nfo files or the other way around.

You essentially have data and no agebt to support it locally. There is nno alternative than to add it to the metadata database like thetvdb as it will sort the question of the uniqueid to use. Yes you could fake it in the nfo file but that's not a solution....

**Comment by ZeroQI** [comment]
Plex metadata agent search function assign a unique id, and the update function docnload the metadata for that id... You answer need to emcompass that truth.

You propertly need one unique id for the metadata agent, now uou can vustom select one agent for one series in alibrary to make it work, but so far has not indicated one database that knows that series so there is only one outcome, adding it yourself...

**Comment by docbill** [comment]
```
  <uniqueid type="tvdb" default="false">-1</uniqueid>
  <uniqueid type="imdb" default="false">tt7188852</uniqueid>
  <uniqueid type="tmdb" default="true">530495</uniqueid>
```

If there was an imdb search the unique id problem would be solved.

**Comment by docbill** [comment]
In more detail this is the full tvshows.nfo file:

```
<?xml version="1.0" encoding="utf-8"?>
<tvshow>
  <title>Tabitha: Witch of the Order</title>
  <ratings>
    <rating name="tvdb" max="10" default="true">
      <value>0</value>
    </rating>
  </ratings>
  <originaltitle>Tabitha: Witch of the Order</originaltitle>
  <sorttitle>Tabitha: Witch of the Order</sorttitle>
  <id>530495</id>
  <runtime>60</runtime>
  <premiered>2017-10-30T00:00:00Z</premiered>
  <year>2017</year>
  <status>Released</status>
  <plot>In modern-day Seattle a rookie witch teams up with a grizzled priest to stop a coven of rogue witches and uncover the trut
h behind magic's reemergence.</plot>
  <outline>In modern-day Seattle a rookie witch teams up with a grizzled priest to stop a coven of rogue witches and uncover the t
ruth behind magic's reemergence.</outline>
  <tagline></tagline>
  <set></set>
  <trailer></trailer>
  <uniqueid type="tvdb" default="false">-1</uniqueid>
  <uniqueid type="imdb" default="false">tt7188852</uniqueid>
  <uniqueid type="tmdb" default="true">530495</uniqueid>
  <genre>Fantasy</genre>
  <director>James Dailey</director>
  <actor>
    <name>Mahria Zook</name>
    <role>Hester</role>
    <order>1</order>
    <thumb>https://image.tmdb.org/t/p/original/tJFHAWIhcfCd2oJYnoyZiJNSKpp.jpg</thumb>
  </actor>
  <thumb aspect="poster" preview="">https://image.tmdb.org/t/p/w600_and_h900_bestv2/ndOKLQVbEh1dOiXlMPjzRAz8aNg.jpg</thumb>
</tvshow>
```

This was created via an offline media scanner.

**Comment by docbill** [comment]
The fact it grabbed a date for the movie not series, indicates to me the offline scanner probably didn't distiquish which result it needed.

**Comment by ZeroQI** [comment]
You have themoviedb agent though...
And if not you can use hama forced id [tmdb-530495] for movies or [tsdb-530495] for series...
There can be issues with an id existing for both movies and a different series. That is how i solved it.
Install an agent abd match mabually selexting the agent and title and then it is properly in plex with proper metadata

**Comment by docbill** [comment]
In the end these are niche scenarios, so I can understand if you don't want to support them in your code.   But providing you the information might help build the case as to how you do want to expand the tool in the future.

**Comment by docbill** [comment]
Your responses also give me a better idea that if I decide to the update, if I should consider it a permanent fork, or if the PR has a decent chance of being merged.

**Comment by ZeroQI** [comment]
Online VOD storefront are not a valid sources for series info, unless they are the network of origin, TheTVDB is only for what was shown on TV initially. You should be able to add it
Tvguide has it as a series. 

I feel like they cut the movie into 15 min series episodes in 2019... You need to find posters and actor pics and summary and submit it to thetvdb and themobiedb series
