### ISSUE TITLE
Really love this!

### ISSUE THREAD

**Issue by peva3** [ZeroQI/Lambda.bundle#5]
Just got it setup on my server and I can see it going through and saving all the metadata. I think this could be a really great plugin for people using Gdrive Rclone mounts for plex servers. You wouldn't have to waste time with the ridiculously slow library scans, it would just pull the metadata straight from the files. 

Quick questions:

1. is there a standard metadata format you are using here for the .nfo? For example, would Emby be able to understand this information without having to be reformatted at all?

2. What is the process like when metadata is updated? Do the files get automatically updated?

3. For importing on a new server, I assume you would just enable the agent, then create/refresh libraries and it would just pull in all the metadata, or is there anything else you would need to do? Does the position of Lambda in the Agent list effect it working correctly? (Does Lambda need to be at the top of the list to make sure it's being used first?).

Thanks!

**Comment by ZeroQI** [comment]
- am trying to be XBMC NFO compatible https://kodi.wiki/view/NFO_files/TV_shows
- it by default save plex info and put it locally. if present locally and not in Plex it updates Plex (naming is local media assets compatible so i need no code for posters fanart and theme songs)
- well if you want to import from NFO i will set up a direction when local and Plex metadata conflicts. It is a secondary agent so last in the list is fine

Just fixed xml adding function so can work on updating plex from nfo, need to test that
